config/routes.rb
DelayedGram::Application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  root 'posts#index'
  resources :posts do
  	resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, :user_id, presence: true
	belongs_to :user
	has_many :comments, dependent: :destroy
  
  has_attached_file :image, styles: {:medium => "640x"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :user_name, presence: true, length: { minimum: 4, maximum: 20 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_post

def create
  @comment = @post.comments.build(comment_params)
  @comment.user_id = current_user.id

  if @comment.save
    flash[:success] = "congratz"
    redirect_to :back
  else
    flash[:alert] = "wtf man?"
    render root_path
  end
end
def new
end
def destroy  
  @comment = @post.comments.find(params[:id])

  @comment.destroy
  flash[:success] = "Comment deleted :("
  redirect_to root_path
end  


private

def comment_params  
  params.require(:comment).permit(:content)
end

def set_post  
  @post = Post.find(params[:post_id])
end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
	before_action :authenticate_user!, :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end
	def new
		@post = current_user.posts.build
	end
	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			flash[:success] = "Your post has been created!"
			redirect_to posts_path
		else
			flash.now[:alert] = "Your new post couldn't be created, try again noob!"
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash.now[:success] = "Post updated."
			redirect_to(post_path(@post))
		else
			flash.now[:alert] = "Update failed, what is wrong with you?"
			render :new
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params  
  		params.require(:post).permit(:image, :caption)
	end

	def set_post
	@post = Post.find(params[:id])  
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
def alert_for(flash_type)  
	  { success: 'alert-success',
	    error: 'alert-danger',
	    alert: 'alert-warning',
	    notice: 'alert-info'
	  }[flash_type.to_sym] || flash_type.to_s
	end  
end

app/helpers/comments_helper.rb
module CommentsHelper
	def time post
		time_ago_in_words(post.created.from_now)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def time f
		time_ago_in_words f.from_now
	end
end

app/views/layouts/_navbar.html.erb
<div class="navbar-header row">
	<div class="offset-by-one three columns">
		<a class="navbar-brand button" href="/"><h4>Delayedgram</h4></a>
	</div>
	<% if user_signed_in? %>
	<div class="offset-by-two three columns button">
		<%= link_to "New Post", new_post_path %>    	    
	</div>
	<div class="three columns button">
		<%= link_to "Logout", destroy_user_session_path, method: :delete %>
	</div>

	<% else %>
	<div class="navbar-header row">
		<div class="offset-by-two three columns button">
			<%= link_to "Login", new_user_session_path %>
		</div>
		<div class="three columns button">
			<%= link_to "Sign up", new_user_registration_path %>
		</div>

		<% end %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DelayedGram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Jockey+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Padauk" rel="stylesheet">
</head>
<body>

  <div class="container">
   
    <%= render 'layouts/navbar' %>
    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: [:alert, alert_for(name)]%>
    <% end %>
    <%= yield %>

  </div>
</body>
</html>

app/views/posts/edit.html.erb
<div class="row">
	<div class="twelve columns post-form">
		<%= image_tag @post.image.url(:medium) %>
		<%= simple_form_for @post do |f| %>
		  	<%= f.input :image %>
		  	<%= f.input :caption %>
		  	<%= f.button :submit %>
  		<% end %>
  		<div align="center" class="edit">
  			<div class="button edit-button">
  				<%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this?"} %>
  			</div>
  			<div class="button edit-button">
  				<%= link_to "Cancel", posts_path %>
  			</div>
  		</div>
  	</div>
 </div>

app/views/posts/index.html.erb
<div class="row post-view">

	
	<div class="offset-by-one ten columns post-main">

		<% @posts.reverse.each do |post| %>
		<div class="post-user">
			<%= post.user.user_name %>
		</div>
			<%= link_to (image_tag post.image.url(:medium)), post_path(post) %>
		<div class="post-caption">
			<%= post.caption %>
			<h6>
			posted <%= time_ago_in_words post.created_at %> ago.
			</h6>
		</div>
		<div class="comments-section">	
			<% if post.comments %>
			<div class="comments">
				<% post.comments.each do |comment| %>
					<div><%= comment.user.user_name %></div>
					 "<%= comment.content %>"
					posted <%= time_ago_in_words comment.created_at %> ago.
					<% if comment.user == current_user %>
					  <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "fo real?" } do 
					  	image_tag "http://www.drodd.com/images14/x15.jpg", :size => '10x10' end%>
        		<% end %>
				<% end %>
			<% end %>
			</div>
		<%= form_for [post, post.comments.new] do |f| %>

		<%= f.text_field :content, placeholder: 'Add a comment...'%>

		<% end %> 
		</div>
		<% end %>
	</div>

</div>

app/views/posts/new.html.erb
<div class="row">
	<div class="twelve columns post-form">
	<%= simple_form_for @post do |f| %>

  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
  <% end %>
  </div>
 </div>

app/views/posts/show.html.erb
<div class="row">
	
	<div class="offset-by-two eight columns show">
		<div class="post-user">
			<%= @post.user.user_name %>
		</div>
		<%= link_to (image_tag @post.image.url(:medium)), post_path %>
		
		<div class="post-caption">
			<%= @post.caption %>
		</div>
		<% if @post.user.id == current_user.id %>

		<%= link_to "Edit Post", edit_post_path(@post) %>
		<% else %>
		<%= link_to "Cancel", posts_path %>
		<% end %>
	</div>
</div>